### ISSUE TITLE
Can't be used as a `route.data`

### ISSUE THREAD

**Issue by matthewp** [canjs/can-define-object#11] opened 2019-06-17 13:34 UTC
Not sure why, something throws when `route.start()` is called.

**Comment by phillipskevin** [comment] 2019-06-19 14:09
Can you share your `route` code? I'm not seeing this issue. https://codepen.io/kphillips86/pen/OebbLV?editors=0011.

**Comment by phillipskevin** [comment] 2019-06-19 17:14
Closing since we can't reproduce. Will re-open if someone else runs into issues.

**Closed by phillipskevin** 2019-06-19 17:14 UTC
Labels: bug
